music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Double))
music.playTone(659, music.beat(BeatFraction.Double))
music.playTone(494, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Double))
music.playTone(523, music.beat(BeatFraction.Double))
music.playTone(659, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Double))
music.playTone(880, music.beat(BeatFraction.Double))
music.playTone(659, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Double))
music.playTone(440, music.beat(BeatFraction.Double))
music.playTone(659, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
